### ISSUE TITLE
Enable raw format for the md2po2md command

### ISSUE THREAD

**Issue by yanedie** [mondeja/mdpo#285] opened 2023-08-22 02:31 UTC
I've read the documentation for a long time and still couldn't find a way to keep the HTML in the .po file. I noted that there was a -x but the option flag is md4c.MD_FLAG_NOHTMLBLOCKS, which means I can only disable the HTML blocks in the output.

**Comment by mondeja** [comment] 2023-08-29 11:57
I don't really understand what are you trying to explain. Could you share a minimal reproducible example?

**Comment by mondeja** [comment] 2023-11-27 18:56
Closing due to lack of additional information. Feel free to reopen with a MRE.

**Closed by mondeja** 2023-11-27 18:56 UTC
